---

name: Lint

on:
  workflow_dispatch:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/lint.yml'
      - 'requirements_lint.txt'
      - 'requirements.txt'
  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/lint.yml'
      - 'requirements_lint.txt'
      - 'requirements.txt'
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements_lint.txt >/dev/null
          pip install -r requirements.txt >/dev/null

      - name: Running PyLint
        run: |
          pylint --version
          bash scripts/lint.sh
