---

name: Test

on:
  workflow_dispatch:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/test.yml'
      - 'requirements.txt'
  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/test.yml'
      - 'requirements.txt'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt install pandoc >/dev/null
          pip install -r requirements.txt >/dev/null

      - name: Running Functional-Test
        run: |
          bash scripts/test.sh
